import type { HostContext, HostHttpClient } from '@liveshops/host-sdk'
import { hostFormModal } from '@liveshops/host-sdk'
import { button, card, dataCard, page, statusLine } from '@liveshops/design-tokens'

interface Credential { id:number;version:number;kind:string;identifier:string;status:string }
interface User { subject:string;displayName:string;principalType:string;subjectStatus:string;subjectVersion:number;memberStatus:string;accessVersion:number;credential:Credential;roleIds:number[];activeSessions:number }
interface Session { id:string;deviceName:string;ipAddress:string;status:string;lastRefreshedAt:string;expiresAt:string }

export async function renderDirectory(root:HTMLElement,api:HostHttpClient,_context:HostContext):Promise<void>{
  const state=statusLine();const body=document.createElement('div');let users:User[]=[]
  const create=hostFormModal({title:'新建平台操作员',fields:[{name:'displayName',label:'姓名',required:true},{name:'username',label:'登录账号',required:true},{name:'password',label:'初始密码',kind:'input',type:'password',required:true},{name:'roleIds',label:'初始角色 ID（逗号分隔）',required:true}],onSubmit:(values,modal)=>{modal.setBusy(true);const id=crypto.randomUUID();api.request('/admin/identity/users',{method:'POST',body:JSON.stringify({idempotencyKey:id,operationId:id,displayName:values.displayName,username:values.username,password:values.password,roleIds:ids(values.roleIds)})}).then(()=>{modal.close();return load()}).catch(e=>modal.setError(String(e))).finally(()=>modal.setBusy(false))}})
  async function load(){state.set('正在加载平台用户…');try{users=await api.request<User[]>('/admin/identity/users');render();state.set(`已加载 ${users.length} 名平台操作员`)}catch(e){state.set(String(e),'danger')}}
  function render(){body.replaceChildren();for(const user of users){const row=document.createElement('section');const title=document.createElement('h2');title.textContent=`${user.displayName} · ${user.credential.identifier}`;const meta=document.createElement('p');meta.textContent=`${user.subjectStatus} · 角色 ${user.roleIds.join(', ')||'-'} · 活动会话 ${user.activeSessions}`;const actions=document.createElement('div');actions.append(button({label:user.subjectStatus==='ACTIVE'?'停用':'启用',variant:'secondary',onClick:()=>void changeStatus(user)}),button({label:'重置密码',variant:'secondary',onClick:()=>reset(user)}),button({label:'会话管理',onClick:()=>void sessions(user)}));row.append(title,meta,actions);body.append(card({body:row}))}if(!users.length){const empty=document.createElement('p');empty.textContent='暂无平台操作员';body.append(empty)}}
  async function changeStatus(user:User){const target=user.subjectStatus==='ACTIVE'?'DISABLED':'ACTIVE';const modal=hostFormModal({title:`${target==='ACTIVE'?'启用':'停用'} ${user.displayName}`,fields:[{name:'confirm',label:'确认操作',kind:'select',options:['确认'],required:true}],onSubmit:(_values,current)=>{current.setBusy(true);const id=crypto.randomUUID();api.request(`/admin/identity/users/${encodeURIComponent(user.subject)}/${target==='ACTIVE'?'enable':'disable'}`,{method:'POST',body:JSON.stringify({idempotencyKey:id,operationId:id,expectedIdentityVersion:user.subjectVersion,expectedAccessVersion:user.accessVersion})}).then(()=>{current.close();return load()}).catch(e=>current.setError(String(e))).finally(()=>current.setBusy(false))}});modal.open()}
  function reset(user:User){const modal=hostFormModal({title:`重置 ${user.displayName} 的密码`,fields:[{name:'password',label:'新密码',kind:'input',type:'password',required:true}],onSubmit:(values,current)=>{current.setBusy(true);const id=crypto.randomUUID();api.request(`/admin/identity/users/${encodeURIComponent(user.subject)}/credentials/${user.credential.id}/reset`,{method:'POST',body:JSON.stringify({idempotencyKey:id,operationId:id,password:values.password,expectedCredentialVersion:user.credential.version})}).then(()=>{current.close();return load()}).catch(e=>current.setError(String(e))).finally(()=>current.setBusy(false))}});modal.open()}
  async function sessions(user:User){try{const values=await api.request<Session[]>(`/admin/identity/users/${encodeURIComponent(user.subject)}/sessions`);const options=['全部活动会话',...values.map(x=>`${x.id} · ${x.status} · ${x.deviceName||'未知设备'} · ${x.ipAddress||'-'}`)];const modal=hostFormModal({title:`${user.displayName} · 会话管理`,fields:[{name:'session',label:'选择要撤销的会话',kind:'select',options,required:true}],onSubmit:(form,current)=>{current.setBusy(true);const selected=form.session==='全部活动会话'?'':form.session.split(' · ')[0];const id=crypto.randomUUID();const path=selected?`/admin/identity/users/${encodeURIComponent(user.subject)}/sessions/${encodeURIComponent(selected)}/revoke`:`/admin/identity/users/${encodeURIComponent(user.subject)}/sessions/revoke-all`;api.request(path,{method:'POST',body:JSON.stringify({idempotencyKey:id,operationId:id})}).then(()=>{current.close();return load()}).catch(e=>current.setError(String(e))).finally(()=>current.setBusy(false))}});modal.open()}catch(e){state.set(String(e),'danger')}}
  root.replaceChildren(page({showSummary:false,children:dataCard({title:'平台操作员列表',actions:[button({label:'刷新',variant:'secondary',onClick:()=>void load()}),button({label:'新建平台操作员',onClick:()=>create.open()})],status:state.element,body})}));await load()
}
function ids(value:string):number[]{return value.split(',').map(x=>Number(x.trim())).filter(x=>Number.isSafeInteger(x)&&x>0)}
