name: liveshop-identity-test
services:
  identity-migrate:
    image: ${LIVESHOP_IMAGE_PREFIX}/backend:${LIVESHOP_IMAGE_TAG}
    build: !reset null
  identity:
    image: ${LIVESHOP_IMAGE_PREFIX}/backend:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["127.0.0.1:18092:18092"]
  identity-admin:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-admin:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:15201:18080"]
  identity-merch:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-merch:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:15202:18080"]
  identity-shop:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-shop:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:15203:18080"]
  identity-live:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-live:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:15204:18080"]
