name: liveshop-identity-test
services:
  identity-migrate:
    image: ${LIVESHOP_IMAGE_PREFIX}/backend:${LIVESHOP_IMAGE_TAG}
    build: !reset null
  identity:
    image: ${LIVESHOP_IMAGE_PREFIX}/backend:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["127.0.0.1:18092:8092"]
  identity-admin:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-admin:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:5201:8080"]
  identity-merch:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-merch:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:5202:8080"]
  identity-shop:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-shop:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:5203:8080"]
  identity-live:
    image: ${LIVESHOP_IMAGE_PREFIX}/frontend-live:${LIVESHOP_IMAGE_TAG}
    build: !reset null
    ports: !override ["192.168.5.140:5204:8080"]
